src/Entity/Reponse.php
<?php

namespace App\Entity;

use App\Repository\ReponseRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ReponseRepository::class)
 */
class Reponse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=250)
     * @Assert\NotBlank(message="Reponse  is required")
     */
    private $reponse_1;

    /**
     * @ORM\Column(type="string", length=250)
     * @Assert\NotBlank(message="Code is required")
     */
    private $reponse_2;

    /**
     * @ORM\Column(type="string", length=250)
     * @Assert\NotBlank(message="Reponse is required")
     */
    private $reponse_3;

    /**
     * @ORM\OneToOne(targetEntity=Question::class, cascade={"persist", "remove"})
     * @Assert\NotBlank(message="Reponse is required")
     */
    private $question;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReponse1(): ?string
    {
        return $this->reponse_1;
    }

    public function setReponse1(string $reponse_1): self
    {
        $this->reponse_1 = $reponse_1;

        return $this;
    }

    public function getReponse2(): ?string
    {
        return $this->reponse_2;
    }

    public function setReponse2(string $reponse_2): self
    {
        $this->reponse_2 = $reponse_2;

        return $this;
    }

    public function getReponse3(): ?string
    {
        return $this->reponse_3;
    }

    public function setReponse3(string $reponse_3): self
    {
        $this->reponse_3 = $reponse_3;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }
}

src/Form/ReponseType.php
<?php

namespace App\Form;

use App\Entity\Question;
use App\Entity\Reponse;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReponseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('reponse_1')
            ->add('reponse_2')
            ->add('reponse_3')
            ->add('question',EntityType::class,[
                'class'=>Question::class,
                'choice_label'=>function(Question $question) {
                    return sprintf(' %s    / %s /', $question->getQuestionA(), $question->getType());
                }
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reponse::class,
        ]);
    }
}

src/Controller/ReponseController.php
<?php

namespace App\Controller;

use App\Entity\Reponse;
use App\Form\ReponseType;
use App\Repository\ReponseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reponse")
 */
class ReponseController extends AbstractController
{
    /**
     * @Route("/", name="reponse_index", methods={"GET"})
     */
    public function index(ReponseRepository $reponseRepository): Response
    {
        return $this->render('reponse/index.html.twig', [
            'reponses' => $reponseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="reponse_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reponse = new Reponse();
        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reponse);
            $entityManager->flush();

            return $this->redirectToRoute('reponse_index');
        }

        return $this->render('reponse/new.html.twig', [
            'reponse' => $reponse,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reponse_show", methods={"GET"})
     */
    public function show(Reponse $reponse): Response
    {
        return $this->render('reponse/show.html.twig', [
            'reponse' => $reponse,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reponse_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reponse $reponse): Response
    {
        $form = $this->createForm(ReponseType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reponse_index');
        }

        return $this->render('reponse/edit.html.twig', [
            'reponse' => $reponse,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reponse_delete", methods={"POST"})
     */
    public function delete(Request $request, Reponse $reponse): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reponse->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reponse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reponse_index');
    }
}

templates/reponse/_delete_form.html.twig
<form method="post" action="{{ path('reponse_delete', {'id': reponse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reponse.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reponse/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}

<div class="card-content">
    <div class="card-body">
        <fieldset>
            <div class="input-group">


                {{ form_widget(form.reponse_1,{'attr':{'class':'form-control','placeholder':'la reponse juste ','style':"width: 200px;"} } ) }}
            </div>
        </fieldset>
        {{ form_errors(form.reponse_1) }}
    </div>
</div>
<div class="card-content">
    <div class="card-body">
        <fieldset>
            <div class="input-group">


                {{ form_widget(form.reponse_2,{'attr':{'class':'form-control','placeholder':'Reponse fausse 1','style':"width: 200px;"} } ) }}
            </div>
        </fieldset>
        {{ form_errors(form.reponse_2) }}
    </div>
</div>
<div class="card-content">
    <div class="card-body">
        <fieldset>
            <div class="input-group">


                {{ form_widget(form.reponse_3,{'attr':{'class':'form-control','placeholder':'Reponse fausse 2','style':"width: 200px;"} } ) }}
            </div>
        </fieldset>
        {{ form_errors(form.reponse_3) }}
    </div>
</div>

    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reponse/edit.html.twig
{% extends 'back/index.html.twig' %}
{% block title %}Edit Reponse{% endblock %}

{% block bodyback %}
    <h1>Edit Reponse</h1>

    {{ include('reponse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reponse_index') }}">back to list</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}

templates/reponse/index.html.twig
{% extends 'back/index.html.twig' %}

{% block title %}Reponse index{% endblock %}

{% block bodyback %}
    <h1 style="text-align: center">Reponse Liste</h1>
</br>
    </br>
    <div style="text-align: center">
    <td> <button  type="button" class="btn btn-dark" > <a href="{{ path('reponse_new') }}">Ajouter </a></button></td>
    </div>
    </br>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Reponse_1</th>
                <th>Reponse_2</th>
                <th>Reponse_3</th>
                <th>Afficher</th>
                <th>Modifier</th>
            </tr>
        </thead>
        <tbody>
        {% for reponse in reponses %}
            <tr>
                <td>{{ reponse.id }}</td>
                <td>{{ reponse.reponse1 }}</td>
                <td>{{ reponse.reponse2 }}</td>
                <td>{{ reponse.reponse3 }}</td>
                <td>
                    <button  type="button" class="btn btn-dark" >
                    <a href="{{ path('reponse_show', {'id': reponse.id}) }}">Afficher</a>
                    </button>

                </td>
                <td> <button  type="button" class="btn btn-dark" >
                        <a href="{{ path('reponse_edit', {'id': reponse.id}) }}">Modifier</a>
                    </button></td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/reponse/new.html.twig
{% extends 'back/index.html.twig' %}

{% block title %}New Reponse{% endblock %}

{% block bodyback %}
    <h1>Create new Reponse</h1>

    {{ include('reponse/_form.html.twig') }}

    <a href="{{ path('reponse_index') }}">back to list</a>
{% endblock %}

templates/reponse/show.html.twig
{% extends 'back/index.html.twig' %}
{% block title %}Reponse{% endblock %}

{% block bodyback %}
    <h1>Reponse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reponse.id }}</td>
            </tr>
            <tr>
                <th>Reponse_1</th>
                <td>{{ reponse.reponse1 }}</td>
            </tr>
            <tr>
                <th>Reponse_2</th>
                <td>{{ reponse.reponse2 }}</td>
            </tr>
            <tr>
                <th>Reponse_3</th>
                <td>{{ reponse.reponse3 }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reponse_index') }}">back to list</a>

    <a href="{{ path('reponse_edit', {'id': reponse.id}) }}">edit</a>

    {{ include('reponse/_delete_form.html.twig') }}
{% endblock %}