src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity(repositoryClass=ReclamationRepository::class)
 */
class Reclamation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Commentaire is required")
     * @Assert\Length(
     *     min = 4,
     *     max= 255,
     *     minMessage = "Le commentaire doit comporter au moins {{ limit }} caractéres",
     *     maxMessage = "Le commentaire doit comporter au plus {{ limit }} caractéres"
     * )
     */
    private $commentaire;

    /**
     * @ORM\Column(type="date")

     */
    private $date_reclamation;

    /**
     * @ORM\Column(type="string")
     * @ORM\Column(type="string",length=255)
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="Reclamation")
     */
    private $categorie;

    /**
     * @ORM\Column(type="integer")
     */
    private $idClient;

    /**
     * @ORM\OneToMany(targetEntity=Traitement::class, mappedBy="id_reclamation")
     */
    private $traitements;







    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->traitements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getDateReclamation(): ?\DateTimeInterface
    {
        return $this->date_reclamation;
    }

    public function setDateReclamation(): self
    {
        $this->date_reclamation = new \DateTime('now');

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getCategories(): ArrayCollection
    {
        return $this->categories;
    }

    /**
     * @param ArrayCollection $categories
     */
    public function setCategories(ArrayCollection $categories): void
    {
        $this->categories = $categories;
    }

    /**
     * @return mixed
     */
    public function getIdClient()
    {
        return $this->idClient;
    }

    /**
     * @param mixed $idClient
     */
    public function setIdClient(): void
    {
        $this->idClient = 1;
    }

    /**
     * @return Collection|Traitement[]
     */
    public function getTraitements(): Collection
    {
        return $this->traitements;
    }

    public function addTraitement(Traitement $traitement): self
    {
        if (!$this->traitements->contains($traitement)) {
            $this->traitements[] = $traitement;
            $traitement->setIdReclamation($this);
        }

        return $this;
    }

    public function removeTraitement(Traitement $traitement): self
    {
        if ($this->traitements->removeElement($traitement)) {
            // set the owning side to null (unless already changed)
            if ($traitement->getIdReclamation() === $this) {
                $traitement->setIdReclamation(null);
            }
        }

        return $this;
    }



}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Reclamation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Captcha\Bundle\CaptchaBundle\Form\Type\CaptchaType;


class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('commentaire')
            ->add('captcha', \Gregwar\CaptchaBundle\Type\CaptchaType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Reclamation;
use App\Form\ReclamationType;
use App\Repository\ReclamationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;


/**
 * @Route("/reclamation")
 */
class ReclamationController extends AbstractController
{
    /**
     * @Route("/", name="reclamation_index", methods={"GET"})
     */
    public function index(ReclamationRepository $reclamationRepository): Response
    {

        return $this->render('reclamation_admin/index.html.twig', [
            'reclamations' => $reclamationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/traite", name="reclamation_index_traite", methods={"GET"})
     */
    public function FindbyTraite(ReclamationRepository $reclamationRepository): Response
    {

        return $this->render('reclamation_admin/index.html.twig', [
            'reclamations' => $reclamationRepository->findby(array('etat'=>"Traité")),
        ]);
    }
    /**
     * @Route("/nontraite", name="reclamation_index_nontraite", methods={"GET"})
     */
    public function FindbyNonTraite(ReclamationRepository $reclamationRepository): Response
    {

        return $this->render('reclamation_admin/index.html.twig', [
            'reclamations' => $reclamationRepository->findby(array('etat'=>"Non Traité")),
        ]);
    }

    /**
     * @Route("/im", name="im", methods={"GET"})
     */
    public function imp(ReclamationRepository $reclamationRepository): Response
    {
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);



        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('reclamation_admin/imp.html.twig',
            [ 'reclamations' => $reclamationRepository->findAll(),
            ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("reclamations.pdf", [
            "Attachment" => true
        ]);

        return $this->render('reclamation_admin/index.html.twig', [
            'reclamations' => $reclamationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{titre}", name="reclamation_new", methods={"GET","POST"})
     */
    public function new($titre,Request $request): Response
    {
        $reclamation = new Reclamation();
        $categorie = new Categorie();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);
        $reclamation->setIdClient();
        $reclamation->setDateReclamation();
        $categorie->setType($titre);
        $reclamation->setCategorie($categorie);
        $reclamation->setEtat("Non Traité");
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($categorie);
            $entityManager->persist($reclamation);
            $entityManager->flush();

            return $this->redirectToRoute('reclamation_showByUser',["id"=>1]);
        }

        return $this->render('reclamation/new.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reclamation_show", methods={"GET"})
     */
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }
    /**
     * @Route("/reclamation_back/{id}", name="reclamation_show_admin", methods={"GET"})
     */
    public function showAdmin(Reclamation $reclamation): Response
    {
        return $this->render('reclamation_admin/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }
    /**
     * @Route("/ReclamationsClients/{id}", name="reclamation_showByUser", methods={"GET"})
     */
    public function showByUser(int $id,ReclamationRepository $reclamationRepo): Response
    {
        $reclamations = $reclamationRepo->findBy(array("idClient"=>$id));

        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamations,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reclamation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reclamation $reclamation , ReclamationRepository $reclamationRepo): Response
    {
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $reclamations = $reclamationRepo->findBy(array("idClient"=>1));
            return $this->render('reclamation/index.html.twig', [
                'reclamations' => $reclamations,
            ]);
        }

        return $this->render('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reclamation_delete", methods={"POST"})
     */
    public function delete(Request $request, Reclamation $reclamation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reclamation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reclamation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reclamation_index');
    }

    /**
     * @Route("/deleteFront/{id}", name="reclamation_delete_client", methods={"POST"})
     */
    public function deleteClient(Request $request, Reclamation $reclamation , ReclamationRepository $reclamationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reclamation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reclamation);
            $entityManager->flush();
        }

        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamationRepository->findAll(),
        ]);
    }



    /**
     * @param reclamationRepository $rep
     * @param Request $req
     * @return Response
     * @Route("/reclamation/search_admin",name="recherche_admin")
     */
    public function search(reclamationRepository $reclamationRepository,Request $req)
    {
        $data=$req->get('rs');

        $reclamation=$reclamationRepository->findBy(['commentaire'=>$data]);


        return $this->render('reclamation_admin/index.html.twig',[
            'reclamations'=>$reclamation,

        ]);


    }

    /**
     * @param reclamationRepository $rep
     * @param Request $req
     * @return Response
     * @Route("/reclamation/search",name="recherche")
     */
    public function search2(reclamationRepository $reclamationRepository,Request $req)
    {
        $data=$req->get('rs');

        $reclamation=$reclamationRepository->findBy(['commentaire'=>$data]);


        return $this->render('reclamation/index.html.twig',[
            'reclamations'=>$reclamation,

        ]);


    }




}

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('reclamation_delete_client', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <div style="text-align: center" >
        <button class="btn btn-dark" class="btn">Supprimer</button>
    </div>
</form>

templates/reclamation/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
<div class="card-content">
    <div class="card-body">
        <fieldset>
            <div class="input-group">
                {{ form_errors(form.commentaire) }}
                {{ form_label(form.commentaire,"Commentaire : ") }}
                {{ form_widget(form.commentaire,{'attr':{'class':'form-control','style':"width: 200px;margin-left:30px "} } ) }}
            </div>
        </fieldset>
    </div>
</div>

<div class="card-content">
    <div class="card-body">
        <fieldset>
            <div class="input-group">
                {{ form_errors(form.captcha) }}
                {{ form_label(form.captcha,"Captcha : ") }}
                {{ form_widget(form.captcha,{'attr':{'class':'form-control','style':"width: 200px;margin-left:30px "} } ) }}
            </div>
        </fieldset>
    </div>
</div>




<div style="text-align: center">
    <button  class="btn btn-dark">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/reclamation/edit.html.twig
{% extends 'back/base.html.twig' %}
{% block title %}Edit Reclamation{% endblock %}

{% block main %}
    <h1 align="center">MODIFIER RECLAMATION</h1>


    {{ include('reclamation/_form.html.twig', {'button_label': 'Modifier'}) }}

    <div style="text-align: right" >
        <button  class="btn btn-dark" >
            <a href="{{ path('reclamation_showByUser', {'id':1} )}}" align="center">Retour à la liste des réclamations</a>
        </button>
    </div>
{% endblock %}

templates/reclamation/error.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <h1> Une erreur est survenue lors de votre paiement </h1>
{% endblock %}

templates/reclamation/index.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Reclamation index{% endblock %}

{% block main %}
    <h1 align="center"> GESTION RECLAMATIONS </h1>


    {% block search2 %}
        <form method="post" action="{{ path('recherche') }}">
            <li class="nav-item nav-search"><a class="nav-link nav-link-search" href="#"><i class="ficon ft-search" ></i></a>
                <div class="search-input" >
                    <input class="input" type="text" name="rs" placeholder="search...">
                </div>
            </li>
        </form>
    {% endblock %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Categorie</th>
                <th>Commentaire</th>
                <th>Date_reclamation</th>
                <th>Etat</th>
                <th>Afficher</th>
                <th>Modifier</th>

            </tr>
        </thead>
        <tbody>
        {% for reclamation in reclamations %}
            <tr>
                <td>{{ reclamation.id }}</td>
                <td>{{ reclamation.categorie.type }}</td>
                <td>{{ reclamation.commentaire }}</td>
                <td>{{ reclamation.dateReclamation ? reclamation.dateReclamation|date('Y-m-d') : '' }}</td>
                <td>{{ reclamation.etat }}</td>

                <td>
                    <button  type="button" class="btn btn-dark" >
                        <a href="{{ path('reclamation_show', {'id': reclamation.id}) }}">Afficher</a>
                    </button>
                </td>
                <td>
                    <button  type="button" class="btn btn-dark" >
                        <a href="{{ path('reclamation_edit', {'id': reclamation.id}) }}">Modifier</a>
                    </button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/reclamation/new.html.twig
{% extends 'back/base.html.twig' %}
{% block title %}New Reclamation{% endblock %}

{% block main %}

    <h1 style="text-align: center"> AJOUTER UNE NOUVELLE RECLAMATION </h1>
        <div style="text-align: center">
            {{ include('reclamation/_form.html.twig') }}

            <div style="text-align: right" >
                <button  class="btn btn-dark" >
                    <a href="{{ path('reclamation_showByUser', {'id':1} )}}" align="center">Retour à la liste des réclamations</a>
                </button>
            </div>
        </div>
{% endblock %}

templates/reclamation/show.html.twig
{% extends 'back/base.html.twig' %}


{% block title %}Reclamation{% endblock %}

{% block main %}
    <h1 align="center">AFFICHER UNE RECLAMATION</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reclamation.id }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ reclamation.commentaire }}</td>
            </tr>
            <tr>
                <th>Date_reclamation</th>
                <td>{{ reclamation.dateReclamation ? reclamation.dateReclamation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ reclamation.etat }}</td>
            </tr>
        </tbody>
    </table>

    <div style="text-align: right" >
        <button  class="btn btn-dark" >
            <a href="{{ path('reclamation_showByUser', {'id':1} )   }} " align="center">Retour à la liste des réclamations</a>
        </button>
    </div>



    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}