src/Entity/Tag.php
<?php

namespace App\Entity;

use App\Repository\TagRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=TagRepository::class)
 */
class Tag
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups ("Tags:read")
     */
    private $id;

    /**
     *@Assert\NotBlank(message="Titre  is required")
     * @ORM\Column(type="string", length=255)
     * @Groups("Tags:read")
     */
    private $tag_name;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime", nullable=true)

     */
    private $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @Gedmo\Slug(fields={"tag_name"}, updatable=false)
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean")
     */
    private $state;

    public function getId()
    {
        return $this->id;
    }

    public function getTagName()
    {
        return $this->tag_name;
    }

    public function setTagName(string $tag_name)
    {
        $this->tag_name = $tag_name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getState(): ?bool
    {
        return $this->state;
    }

    public function setState(bool $state): self
    {
        $this->state = $state;

        return $this;
    }
}

src/Form/TagType.php
<?php

namespace App\Form;

use App\Entity\Tag;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TagType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tag_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tag::class,
        ]);
    }
}

src/Controller/TagController.php
<?php

namespace App\Controller;

use App\Entity\Tag;
use App\Form\TagType;
use App\Repository\TagRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Encoder\JsonEncoder;

/**
 * @Route("/tag")
 */
class TagController extends AbstractController
{
    /**
     * @Route("/ajax", name="search_tag", methods={"GET"})
     */
    public function searchStudentx(Request $request,NormalizerInterface $Normalizer,TagRepository $tagRepository): Response
    {

        $requestString=$request->get('searchValue');
        $students = $tagRepository->search($requestString);
        $jsonContent = $Normalizer->normalize($students, 'json',['groups'=>'Tag:read']);
        $retour=json_encode($jsonContent);
        return new Response($retour);

    }

    /**
     * @Route("/tag_removed", name="tag_removed", methods={"GET"})
     */
    public function index_removed(TagRepository $tagRepository): Response
    {
        return $this->render('tag/index.html.twig', [
            'tags' => $tagRepository->removed(),
        ]);
    }
    /**
     * @Route("/", name="tag_index", methods={"GET"})
     */
    public function index(TagRepository $tagRepository): Response
    {
        return $this->render('tag/index.html.twig', [
            'tags' => $tagRepository->ff(),
        ]);
    }

    /**
     * @Route("/new", name="tag_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $tag = new Tag();
        $form = $this->createForm(TagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tag);
            $entityManager->flush();

            return $this->redirectToRoute('tag_index');
        }

        return $this->render('tag/new.html.twig', [
            'tag' => $tag,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="tag_show", methods={"GET"})
     */
    public function show(Tag $tag): Response
    {
        return $this->render('tag/show.html.twig', [
            'tag' => $tag,
        ]);
    }


    /**
     * @Route("/{slug}/edit", name="tag_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tag $tag): Response
    {
        $form = $this->createForm(TagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('tag_index');
        }

        return $this->render('tag/edit.html.twig', [
            'tag' => $tag,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/state/{slug}", name="tag_state", methods={"GET"})
     */
    public function delete1(Request $request,TagRepository $tagRepository): Response
    {
        $requestString=$request->get('slug');
       $tagRepository->update_state($requestString);
        return $this->redirectToRoute('tag_index');
    }

    /**
     * @Route("/{slug}", name="tag_delete", methods={"POST"})
     */
    public function delete(Request $request, Tag $tag): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tag->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tag);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tag_index');
    }








}

templates/tag/_delete_form.html.twig
<form method="post" action="{{ path('tag_delete', {'slug': tag.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tag.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tag/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
<div class="card-content">
    <div class="card-body">
        <fieldset>
            <div class="input-group">

                {{ form_widget(form.tag_name,{'attr':{'class':'form-control','placeholder':'Nom de la publicite','style':"width: 200px;"} } ) }}

                {{ form_errors(form.tag_name) }}
            </div>
        </fieldset>
    </div>
</div>



<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form)}}

templates/tag/edit.html.twig
{% extends 'back/index.html.twig' %}
{% block title %}Edit Tag{% endblock %}

{% block bodyback %}
    <h1>Edit Tag</h1>

    {{ include('tag/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('tag_index') }}">back to list</a>

    {{ include('tag/_delete_form.html.twig') }}
{% endblock %}

templates/tag/index.html.twig
{% extends 'back/index.html.twig' %}

{% block lien %}
    <link rel="apple-touch-icon" href="../../../app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="../../../app-assets/images/ico/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i"
          rel="stylesheet">
    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="../../../app-assets/css/vendors.css">
    <!-- END VENDOR CSS-->
    <!-- BEGIN STACK CSS-->
    <link rel="stylesheet" type="text/css" href="../../../app-assets/css/app.css">
    <!-- END STACK CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="../../../app-assets/css/core/menu/menu-types/vertical-menu.css">
    <!-- END Page Level CSS-->
    <!-- BEGIN Custom CSS-->
    <link rel="stylesheet" type="text/css" href="../../../assets/css/style.css">

{% endblock %}
{% block bodyback %}
    <a class="btn btn-primary " href="{{ path('tag_removed') }}">Tags Removed </a>
    <a class="btn btn-primary " href="{{ path('tag_index') }}">Active Tags </a>

    <a class="btn btn-primary btn-block" href="{{ path('tag_new') }}">Create new</a>

<input type="text" id="search" class="form-control" placeholder="Search">

<table class="table" id="t">

    <tr>
        <th>Id</th>
        <th>Tag_name</th>
        <th>Actions</th>
    </tr>

    <tbody id="all">
    {% for tag in tags %}
        <tr>
            <td>{{ tag.id }}</td>
            <td>{{ tag.tagName }}</td>
            <td>
                <a href="{{ path('tag_show', {'slug': tag.slug}) }}">show</a>
                <a href="{{ path('tag_edit', {'slug': tag.slug}) }}">edit</a>
                <a href="{{ path('tag_state', {'slug': tag.id}) }}">delete</a>


            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="3">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
    <tbody id="search"></tbody>




</table>
    <canvas id="doughnut-chart" width="800" height="450"></canvas>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $( document ).ready(function() {
        $("#search").keyup(function(e){
            /* La variable value va prendre la valeur insérer dans le champ de texte afin d’effectuer la recherche */
            var value = $(this).val();
            /* Ajax est lancé lors du remplissage du champ texte dont l’id est « search » pour faire la recherche */
            $.ajax({
                /* l’url est une chaine de caractères contenant l’adresse où la requête est envoyée */
                url : "{{ path('search_tag') }}",
                /* La méthode utilisée pour transférer les données est GET */
                type : 'GET',
                /*Ici search value va prendre la chaine entrée par un utilisateur dans la zone de recherche et sera placée après l’url */
                data: {
                    'searchValue' : value
                },
                /*Cette fonction permet de vider le contenu du tableau pour recevoir le nouveau contenu*/
                success : function(retour){
                    if(retour) {
                        console.log(retour);
                        $('#t tbody#search').empty();
                        $.each(JSON.parse(retour), function(i, obj) {
                            $('#t tbody#all').hide();
                            $('#t tbody#search').append('<tr><td>'+obj.id+'</td><td>'+obj.tag_name+'  </td><td><a href="'+obj.slug+'">SHOW</a> </br><a href="'+obj.slug+'/edit">edit</a> <a href="state/'+obj.id+'">delete</a></td></tr>');
                        });

                                  }
                    else
                    {
                        $('#t tbody#all').show();
                        $('#t tbody#search').empty();
                        $('#t tbody#search').fadeIn('fast');
                    }
                },
            });
            return false;
        });
    });
</script>
    <script>
        new Chart(document.getElementById("doughnut-chart"), {
            type: 'doughnut',
            data: {
                labels: [""],
                datasets: [
                    {
                        label: "",
                        backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
                        data: [,]
                    }
                ]
            },
            options: {
                title: {
                    display: true,
                    text: ' tags status  '
                }
            }
        });
    </script>
{% endblock %}

templates/tag/index2.html.twig
    <input type="text" id="search" class="form-control" placeholder="Search">

<table class="table" id="t">

    <tr>
        <th>Id</th>
        <th>Tag_name</th>
        <th>actions</th>
    </tr>

    <tbody id="all">

    </tbody>
    <tbody id="search"></tbody>




</table>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $( document ).ready(function() {
        $("#search").keyup(function(e){
            /* La variable value va prendre la valeur insérer dans le champ de texte afin d’effectuer la recherche */
            var value = $(this).val();
            /* Ajax est lancé lors du remplissage du champ texte dont l’id est « search » pour faire la recherche */
            $.ajax({
                /* l’url est une chaine de caractères contenant l’adresse où la requête est envoyée */
                url : "{{ path('searchStudentx') }}",
                /* La méthode utilisée pour transférer les données est GET */
                type : 'GET',
                /*Ici search value va prendre la chaine entrée par un utilisateur dans la zone de recherche et sera placée après l’url */
                data: {
                    'searchValue' : value
                },
                /*Cette fonction permet de vider le contenu du tableau pour recevoir le nouveau contenu*/
                success : function(retour){
                    if(retour) {
                        console.log(retour);
                        $('#t tbody#search').empty();
                        $.each(JSON.parse(retour), function(i, obj) {
                            $('#t tbody#all').hide();
                            $('#t tbody#search').append('<tr><td>'+obj.id+'</td><td>'+obj.tag_name+'  </td><td><a href="tag_show/'+obj.slug+'">show</a> </br><a href="tag_edit/'+obj.slug+'">edit</a></td></tr>');
                        });

                                  }
                    else
                    {
                        $('#t tbody#all').show();
                        $('#t tbody#search').empty();
                        $('#t tbody#search').fadeIn('fast');
                    }
                },
            });
            return false;
        });
    });
</script>

templates/tag/new.html.twig
{% extends 'back/index.html.twig' %}

{% block title %}New Tag{% endblock %}

{% block bodyback %}
    <h1>Create new Tag</h1>

    {{ include('tag/_form.html.twig') }}

    <a href="{{ path('tag_index') }}">back to list</a>
{% endblock %}

templates/tag/show.html.twig
{% extends 'back/index.html.twig' %}

{% block title %}Tag{% endblock %}

{% block bodyback %}
    <h1>Tag</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tag.id }}</td>
            </tr>
            <tr>
                <th>Tag_name</th>
                <td>{{ tag.tagName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('tag_index') }}">back to list</a>

    <a href="{{ path('tag_edit', {'slug': tag.slug}) }}">edit</a>

    {{ include('tag/_delete_form.html.twig') }}
{% endblock %}