src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 */
class Question
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=220)
     * @Assert\NotBlank(message="type is required")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=250)
     * @Assert\NotBlank(message="Question is required")
     */
    private $question_a;

    /**
     * @ORM\Column(type="string", length=250)
     * @Assert\NotBlank(message="Reponse is required")
     */
    private $reponse;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     * @Assert\NotBlank(message="Reponse is required")
     */
    private $fausse_reponse;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getQuestionA(): ?string
    {
        return $this->question_a;
    }

    public function setQuestionA(string $question_a): self
    {
        $this->question_a = $question_a;

        return $this;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(string $reponse): self
    {
        $this->reponse = $reponse;

        return $this;
    }

    public function getFausseReponse(): ?string
    {
        return $this->fausse_reponse;
    }

    public function setFausseReponse(?string $fausse_reponse): self
    {
        $this->fausse_reponse = $fausse_reponse;

        return $this;
    }


}

src/Controller/QuestionController1Controller.php
<?php

namespace App\Controller;

use App\Entity\Question;
use App\Form\QuestionType;
use App\Repository\QuestionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/question/controller1")
 */
class QuestionController1Controller extends AbstractController
{
    /**
     * @Route("/", name="question_controller1_index", methods={"GET"})
     */
    public function index(QuestionRepository $questionRepository): Response
    {
        return $this->render('question_controller1/index.html.twig', [
            'questions' => $questionRepository->findAll(),
        ]);
    }
    /**
     * @Route("/stat", name="question_controller1_stat", methods={"GET"})
     */
    public function statsAction()
    {
        $ob = new Highchart();
        $ob->chart->renderTo('linechart');
        $ob->title->text('Browser market shares at a specific website in 2010');
        $ob->plotOptions->pie(array(
            'allowPointSelect'  => true,
            'cursor'    => 'pointer',
            'dataLabels'    => array('enabled' => false),
            'showInLegend'  => true
        ));
        /*$data = array(
             array('Firefox', 45.0),
             array('IE', 26.8),
             array('Chrome', 12.8),
             array('Safari', 8.5),
             array('Opera', 6.2),
             array('Others', 0.7),
         );*/

        // $data = null;

        $liste = $this->getDoctrine()->getManager()->getRepository('AppBundle:question')->stat();

        $ob->series(array(array('type' => 'pie','name' => 'Browser share', 'data' => $liste)));


        return $this->render('AppBundle:Home:stat.html.twig', array(
            'chart' => $ob,
            'liste' => $liste

        ));
    }


    /**
     * @Route("/new", name="question_controller1_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $question = new Question();
        $form = $this->createForm(QuestionType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($question);
            $entityManager->flush();

            return $this->redirectToRoute('question_controller1_index');
        }

        return $this->render('question_controller1/new.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="question_controller1_show", methods={"GET"})
     */
    public function show(Question $question): Response
    {
        return $this->render('question_controller1/show.html.twig', [
            'question' => $question,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="question_controller1_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Question $question): Response
    {
        $form = $this->createForm(QuestionType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('question_controller1_index');
        }

        return $this->render('question_controller1/edit.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="question_controller1_delete", methods={"POST"})
     */
    public function delete(Request $request, Question $question): Response
    {
        if ($this->isCsrfTokenValid('delete'.$question->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($question);
            $entityManager->flush();
        }

        return $this->redirectToRoute('question_controller1_index');
    }


}

templates/question_controller1/_delete_form.html.twig
<form method="post" action="{{ path('question_controller1_delete', {'id': question.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
    <button class="btn">Delete</button>
</form>

templates/question_controller1/_form.html.twig
    {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
    <div class="card-content">
        <div class="card-body">
            <fieldset>
                <div class="input-group">


                    {{ form_widget(form.type,{'attr':{'class':'form-control','placeholder':'Nom de Formation','style':"width: 200px;"} } ) }}
                </div>
            </fieldset>
            {{ form_errors(form.type) }}
        </div>
    </div>

    <div class="card-content">
        <div class="card-body">
            <fieldset>
                <div class="input-group">


                    {{ form_widget(form.question_a,{'attr':{'class':'form-control','placeholder':'Question','style':"width: 200px;"} } ) }}
                </div>
            </fieldset>
            {{ form_errors(form.question_a) }}
        </div>
    </div>
    <div class="card-content">
        <div class="card-body">
            <fieldset>
                <div class="input-group">


                    {{ form_widget(form.reponse,{'attr':{'class':'form-control','placeholder':'La reponse juste','style':"width: 200px;"} } ) }}
                </div>
            </fieldset>
            {{ form_errors(form.reponse) }}
        </div>
    </div>
    <div class="card-content">
        <div class="card-body">
            <fieldset>
                <div class="input-group">


                    {{ form_widget(form.fausse_reponse,{'attr':{'class':'form-control','placeholder':'La fausse Reponse','style':"width: 200px;"} } ) }}
                </div>
            </fieldset>
            {{ form_errors(form.fausse_reponse) }}
        </div>
    </div>

<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/question_controller1/edit.html.twig
{% extends 'back/index.html.twig' %}

{% block bodyback %}
    <h1>Edit Question</h1>

    {{ include('question_controller1/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('question_controller1_index') }}">back to list</a>

    {{ include('question_controller1/_delete_form.html.twig') }}
{% endblock %}

templates/question_controller1/index.html.twig
{% extends 'back/index.html.twig' %}
{% block bodyback %}
    <h1 style="text-align: center">Gestion Question</h1>

    <button  type="button" data-repeater-create class="btn btn-primary">
        <i class="icon-plus4"> <a href="{{ path('question_controller1_new') }}">Ajouter</a></i>
    </button>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Question_a</th>
                <th>Reponse</th>
                <th>Fausse_reponse</th>
                <th>Supprimer</th>
                <th>Modifier</th>
            </tr>
        </thead>
        <tbody>
        {% for question in questions %}
            <tr>
                <td>{{ question.id }}</td>
                <td>{{ question.type }}</td>
                <td>{{ question.questionA }}</td>
                <td>{{ question.reponse }}</td>
                <td>{{ question.fausseReponse }}</td>
                <td>
                    <button  type="button" data-repeater-create class="btn btn-primary">
                    <a href="{{ path('question_controller1_show', {'id': question.id}) }}">Supprimer</a>
                    </button>
                </td>
                <td>
                    <button  type="button" data-repeater-create class="btn btn-primary">
                    <a href="{{ path('question_controller1_edit', {'id': question.id}) }}">Modifier</a>
                    </button>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/question_controller1/new.html.twig
{% extends 'back/index.html.twig' %}
{% block title %}New Question{% endblock %}

{% block bodyback %}
    <h1 style="text-align: center">Create new Question</h1>
    <div style="text-align: center">
        {{ include('question_controller1/_form.html.twig') }}
        <a href="{{ path('question_controller1_index') }}">back to list</a>
    </div>

{% endblock %}

templates/question_controller1/show.html.twig
{% extends 'back/index.html.twig' %}

{% block title %}Question{% endblock %}

{% block bodyback %}
    <h1>Question</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ question.id }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ question.type }}</td>
            </tr>
            <tr>
                <th>Question_a</th>
                <td>{{ question.questionA }}</td>
            </tr>
            <tr>
                <th>Reponse</th>
                <td>{{ question.reponse }}</td>
            </tr>
            <tr>
                <th>Fausse_reponse</th>
                <td>{{ question.fausseReponse }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('question_controller1_index') }}">back to list</a>

    <a href="{{ path('question_controller1_edit', {'id': question.id}) }}">edit</a>

    {{ include('question_controller1/_delete_form.html.twig') }}
{% endblock %}